language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
matrix:
  include:
    - os: osx
      osx_image: xcode11.2  # Python 3.7
      language: shell       # 'language: python' is an error on Travis CI macOS

install: python setup.py install
script: python -m unittest discover
